FONT_TYPE = "Arial"
WINDOW_TITLE = "Password Generator"
FONT_SIZE = 12
FONT_STYLE = "normal"
BACKGROUND_COLOR = "white"
FOREGROUND_COLOR = "black"
ACTIVE_BACKGROUND_COLOR = "#45a049"
INPUT_WEBSITE_WIDTH = 50
INPUT_EMAIL_USERNAME_WIDTH = 50
INPUT_PASSWORD_WIDTH = 19
CANVAS_WIDTH = 200
CANVAS_HEIGHT = 200
CANVAS_IMAGE_POSITION = (100, 100)
CANVAS_BG = (240, 240, 240)
WINDOW_PAD_X = 100
WINDOW_PAD_Y = 100
INPUT_WIDGET_WIDTH = 30
# Constants for the password generator method in main.py file
ALPHABET_CAPS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',]
ALPHABET_LOWER = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
NUMBERS = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
SPECIAL_CHARACTERS = ['!', '#', '$', '&', '_', '*', '.']